name: CD Pipeline - Deploy to EC2

on:
  workflow_run:
    workflows: ["CI Pipeline for bike renting app"]
    types:
      - completed
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name : Pull the bike rent docker image
        env: 
          DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
        run: sudo docker pull $DOCKER_USER/bike_renting_api:latest
      - name: Delete any running container
        run: sudo docker rm -f bike-rent-api-container || true
  
      - name: Run the Bike API container
        env:
          DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
        run: sudo docker run -it -d -p 8001:8001 --name bike-rent-api-container $DOCKER_USER/bike_renting_api:latest
